"""
Generate PowerPoint Presentation for AI Image Detection Project
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

def create_presentation():
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # Slide 1: Title Slide
    slide1 = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    
    # Add background color
    background = slide1.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(26, 35, 126)  # Deep blue
    
    # Title
    title_box = slide1.shapes.add_textbox(Inches(0.8), Inches(2.3), Inches(8.4), Inches(1.2))
    title_frame = title_box.text_frame
    title = title_frame.add_paragraph()
    title.text = "Detecting AI Images Through"
    title.font.size = Pt(48)
    title.font.bold = True
    title.font.color.rgb = RGBColor(255, 255, 255)
    title.alignment = PP_ALIGN.CENTER
    
    title2 = title_frame.add_paragraph()
    title2.text = "JPEG Compression Forensics"
    title2.font.size = Pt(48)
    title2.font.bold = True
    title2.font.color.rgb = RGBColor(255, 255, 255)
    title2.alignment = PP_ALIGN.CENTER
    
    # Subtitle
    subtitle_box = slide1.shapes.add_textbox(Inches(1), Inches(4), Inches(8), Inches(0.8))
    subtitle_frame = subtitle_box.text_frame
    subtitle = subtitle_frame.add_paragraph()
    subtitle.text = "A Machine Learning Approach"
    subtitle.font.size = Pt(28)
    subtitle.font.color.rgb = RGBColor(200, 230, 255)
    subtitle.alignment = PP_ALIGN.CENTER
    
    # Date and accuracy
    stats_box = slide1.shapes.add_textbox(Inches(1), Inches(5), Inches(8), Inches(0.6))
    stats_frame = stats_box.text_frame
    stats = stats_frame.add_paragraph()
    stats.text = "97.2% Accuracy | 348k Training Images | February 2026"
    stats.font.size = Pt(20)
    stats.font.color.rgb = RGBColor(255, 255, 255)
    stats.alignment = PP_ALIGN.CENTER
    
    # Slide 2: What Is This Project?
    slide2 = prs.slides.add_slide(prs.slide_layouts[5])  # Title Only
    title = slide2.shapes.title
    title.text = "What Is This Project?"
    
    content_box = slide2.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "Problem: Can we tell if an image is real or AI-generated?"
    p.font.size = Pt(28)
    p.font.bold = True
    p.space_after = Pt(25)
    
    p = tf.add_paragraph()
    p.text = "Real-World Examples:"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(12)
    
    examples = [
        "📱 Real Photo: Taken with iPhone camera",
        "🤖 AI Image: Generated by Stable Diffusion, DALL-E, Midjourney",
        "❓ Challenge: They look identical to human eyes!"
    ]
    
    for example in examples:
        p = tf.add_paragraph()
        p.text = example
        p.level = 1
        p.font.size = Pt(22)
        p.space_after = Pt(12)
    
    p = tf.add_paragraph()
    p.text = "\nOur Solution: Build a detector using JPEG compression forensics"
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0, 100, 200)
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "Goal: 98%+ accuracy with minimal false positives"
    p.font.size = Pt(22)
    p.font.italic = True
    
    # Slide 3: How JPEG Compression Works
    slide3 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide3.shapes.title
    title.text = "How We Use JPEG Compression"
    
    content_box = slide3.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "What is JPEG Compression?"
    p.font.size = Pt(26)
    p.font.bold = True
    p.space_after = Pt(15)
    
    p = tf.add_paragraph()
    p.text = "When a real camera takes a photo:"
    p.font.size = Pt(22)
    p.font.bold = True
    p.space_after = Pt(10)
    
    camera_steps = [
        "1. Light hits the camera sensor (physical process)",
        "2. Camera converts to pixels",
        "3. JPEG compresses pixels into 8×8 blocks using DCT (math)",
        "4. Creates unique 'fingerprints' from compression"
    ]
    
    for step in camera_steps:
        p = tf.add_paragraph()
        p.text = step
        p.level = 1
        p.font.size = Pt(20)
        p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "\nWhat we detect:"
    p.font.size = Pt(22)
    p.font.bold = True
    p.space_after = Pt(10)
    
    detection_points = [
        "✓ DCT coefficients (compression math patterns)",
        "✓ Blocking artifacts (8×8 grid boundaries)",
        "✓ Benford's Law (natural statistics)",
        "✓ Camera dimension signatures (12MP, 4:3 ratio)"
    ]
    
    for point in detection_points:
        p = tf.add_paragraph()
        p.text = point
        p.level = 1
        p.font.size = Pt(20)
        p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "\nAI images have different compression patterns!"
    p.font.size = Pt(22)
    p.font.bold = True
    p.font.color.rgb = RGBColor(200, 0, 0)
    
    # Slide 4: What About PNG Images?
    slide4 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide4.shapes.title
    title.text = "What About PNG Images?"
    
    content_box = slide4.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "JPEG vs PNG:"
    p.font.size = Pt(26)
    p.font.bold = True
    p.space_after = Pt(15)
    
    # JPEG column
    p = tf.add_paragraph()
    p.text = "📷 JPEG (Our main focus):"
    p.font.size = Pt(22)
    p.font.bold = True
    p.space_after = Pt(10)
    
    jpeg_points = [
        "Lossy compression (loses some data)",
        "Creates compression artifacts we can detect",
        "97.2% accuracy ✓",
        "Most real cameras save as JPEG"
    ]
    
    for point in jpeg_points:
        p = tf.add_paragraph()
        p.text = point
        p.level = 1
        p.font.size = Pt(19)
        p.space_after = Pt(6)
    
    p = tf.add_paragraph()
    p.text = "\n🖼️ PNG (Lossless format):"
    p.font.size = Pt(22)
    p.font.bold = True
    p.space_after = Pt(10)
    
    png_points = [
        "Lossless compression (perfect quality)",
        "No JPEG artifacts to detect",
        "Lower accuracy (not trained on PNG)",
        "Relies more on dimension analysis"
    ]
    
    for point in png_points:
        p = tf.add_paragraph()
        p.text = point
        p.level = 1
        p.font.size = Pt(19)
        p.space_after = Pt(6)
    
    p = tf.add_paragraph()
    p.text = "\nOur model works on both, but best with JPEG!"
    p.font.size = Pt(22)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0, 100, 200)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "(Model trained on 348k JPEG images from real cameras)"
    p.font.size = Pt(18)
    p.font.italic = True
    
    # Slide 5: Our Approach
    slide5 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide5.shapes.title
    title.text = "Our Approach: Forensic Analysis"
    
    content_box = slide5.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "Traditional Method (Failed):"
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = RGBColor(200, 0, 0)
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = '• Deep Learning (ResNet50): "Does this LOOK like AI?"'
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Problem: 100% false positives ❌"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(20)
    
    p = tf.add_paragraph()
    p.text = "Our Method (Success):"
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0, 150, 0)
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = '• Forensics: "How was this created? Check the compression!"'
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Machine Learning (Random Forest) on 70 features"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Result: 97.2% accuracy, 2.6% false positives ✓"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(25)
    
    p = tf.add_paragraph()
    p.text = "Key Insight:"
    p.font.size = Pt(22)
    p.font.bold = True
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "AI can make images that LOOK real"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "But it can't fake the JPEG math patterns from real cameras!"
    p.level = 1
    p.font.size = Pt(20)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0, 100, 200)
    
    # Slide 6: How We Trained the Model
    slide6 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide6.shapes.title
    title.text = "Training Process"
    
    content_box = slide6.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "Training Data:"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(12)
    
    p = tf.add_paragraph()
    p.text = "• 348,385 images total"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "• 120,000 from CIFAKE dataset (objects, scenes)"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "• 140,000 faces dataset (human faces)"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "• Half real photos, half AI-generated"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(20)
    
    p = tf.add_paragraph()
    p.text = "Training Method:"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(12)
    
    p = tf.add_paragraph()
    p.text = "• Extract 70 forensic features from each image"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "• Train Random Forest classifier (300 decision trees)"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "• Offline training on Mac (6-8 hours, CPU-only)"
    p.level = 1
    p.font.size = Pt(22)
    p.space_after = Pt(8)
    
    p = tf.add_paragraph()
    p.text = "• Test on separate validation dataset"
    p.level = 1
    p.font.size = Pt(22)
    
    # Slide 7: Results
    slide7 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide7.shapes.title
    title.text = "Results"
    
    # Main metrics box
    metrics_box = slide7.shapes.add_textbox(Inches(2), Inches(2), Inches(6), Inches(1.5))
    metrics_tf = metrics_box.text_frame
    metrics_tf.word_wrap = True
    
    p = metrics_tf.add_paragraph()
    p.text = "🎯 Overall Accuracy: 97.2%"
    p.font.size = Pt(36)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0, 100, 200)
    p.alignment = PP_ALIGN.CENTER
    
    # Detailed breakdown
    details_box = slide7.shapes.add_textbox(Inches(1.5), Inches(3.8), Inches(7), Inches(2.5))
    details_tf = details_box.text_frame
    details_tf.word_wrap = True
    
    p = details_tf.add_paragraph()
    p.text = "Breakdown:"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(15)
    
    metrics = [
        ("📷 Real Photo Detection", "97.4%"),
        ("🤖 AI Image Detection", "97.0%"),
        ("❌ False Positives", "2.6% (down from 100%!)"),
        ("📊 Training Images", "348,385 images"),
        ("💻 Hardware", "CPU-only (no GPU needed)")
    ]
    
    for metric_name, value in metrics:
        p = details_tf.add_paragraph()
        p.text = f"{metric_name}: {value}"
        p.font.size = Pt(22)
        p.font.bold = True
        p.space_after = Pt(12)
    
    # Slide 8: Demo Application
    slide8 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide8.shapes.title
    title.text = "Web Application Demo"
    
    content_box = slide8.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "Built a Flask Web Interface"
    p.font.size = Pt(26)
    p.font.bold = True
    p.space_after = Pt(20)
    
    p = tf.add_paragraph()
    p.text = "How it works:"
    p.font.size = Pt(22)
    p.font.bold = True
    p.space_after = Pt(12)
    
    web_features = [
        "1. User uploads an image (drag and drop)",
        "2. Model analyzes JPEG compression patterns",
        "3. Checks camera dimension signatures",
        "4. Shows result: Real Photo 📷 or AI-Generated 🤖",
        "5. Displays confidence score (0-100%)"
    ]
    
    for feature in web_features:
        p = tf.add_paragraph()
        p.text = feature
        p.level = 1
        p.font.size = Pt(20)
        p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "\nRuns locally at http://localhost:5001"
    p.font.size = Pt(20)
    p.font.italic = True
    p.space_after = Pt(15)
    
    p = tf.add_paragraph()
    p.text = "Fast: Processes images in under 1 second!"
    p.font.size = Pt(20)
    p.font.bold = True
    p.font.color.rgb = RGBColor(0, 150, 0)
    
    # Slide 9: Future Improvements
    slide9 = prs.slides.add_slide(prs.slide_layouts[5])
    title = slide9.shapes.title
    title.text = "Future Improvements"
    
    content_box = slide9.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
    tf = content_box.text_frame
    tf.word_wrap = True
    
    p = tf.add_paragraph()
    p.text = "1. Improve PNG Detection"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "• Train specifically on PNG images"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Develop PNG-specific forensic features"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(15)
    
    p = tf.add_paragraph()
    p.text = "2. Detect Specific AI Generators"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "• Identify which AI created it (Stable Diffusion, DALL-E, Midjourney)"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Each AI has unique fingerprints"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(15)
    
    p = tf.add_paragraph()
    p.text = "3. Mobile App"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "• iOS/Android app for on-the-go detection"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Check images before sharing on social media"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(15)
    
    p = tf.add_paragraph()
    p.text = "4. Higher Accuracy"
    p.font.size = Pt(24)
    p.font.bold = True
    p.space_after = Pt(10)
    
    p = tf.add_paragraph()
    p.text = "• Target: 99%+ accuracy with <1% false positives"
    p.level = 1
    p.font.size = Pt(20)
    p.space_after = Pt(5)
    
    p = tf.add_paragraph()
    p.text = "• Add more forensic features (currently 70)"
    p.level = 1
    p.font.size = Pt(20)
    
    # Slide 10: Conclusion
    slide10 = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    
    # Background
    background = slide10.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(26, 35, 126)
    
    # Main conclusion
    conclusion_box = slide10.shapes.add_textbox(Inches(1), Inches(1.5), Inches(8), Inches(3))
    conclusion_tf = conclusion_box.text_frame
    conclusion_tf.word_wrap = True
    
    p = conclusion_tf.add_paragraph()
    p.text = "Summary"
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = RGBColor(255, 255, 255)
    p.alignment = PP_ALIGN.CENTER
    p.space_after = Pt(30)
    
    achievements = [
        "✓ Built AI image detector using JPEG compression forensics",
        "✓ Achieved 97.2% accuracy (97.4% real, 97.0% AI)",
        "✓ Fixed 100% false positives → 2.6% false positives",
        "✓ Works on 348k images, CPU-only, offline-capable",
        "✓ Created functional web application demo"
    ]
    
    for achievement in achievements:
        p = conclusion_tf.add_paragraph()
        p.text = achievement
        p.font.size = Pt(22)
        p.font.color.rgb = RGBColor(255, 255, 255)
        p.space_after = Pt(15)
    
    # Final message
    final_box = slide10.shapes.add_textbox(Inches(1), Inches(5.2), Inches(8), Inches(1.5))
    final_tf = final_box.text_frame
    
    p = final_tf.add_paragraph()
    p.text = "Forensic analysis beats deep learning"
    p.font.size = Pt(28)
    p.font.bold = True
    p.font.color.rgb = RGBColor(100, 255, 150)
    p.alignment = PP_ALIGN.CENTER
    p.space_after = Pt(10)
    
    p2 = final_tf.add_paragraph()
    p2.text = "Check the compression, not just the pixels!"
    p2.font.size = Pt(24)
    p2.font.color.rgb = RGBColor(200, 230, 255)
    p2.alignment = PP_ALIGN.CENTER
    
    # Save presentation
    prs.save('AI_Image_Detection_Presentation.pptx')
    print("✓ Presentation created: AI_Image_Detection_Presentation.pptx")
    print("\nSlides created:")
    print("1. Title Slide - AI Image Detection System")
    print("2. What Is This Project? - Problem & Solution")
    print("3. How We Use JPEG Compression - The Science")
    print("4. What About PNG Images? - Format Comparison")
    print("5. Our Approach - Forensic Analysis vs Deep Learning")
    print("6. Training Process - 348k Images")
    print("7. Results - 97.2% Accuracy")
    print("8. Web Application Demo - Live Detection")
    print("9. Future Improvements - What's Next")
    print("10. Summary - Key Takeaways")
    print("\n✅ Presentation ready to explain to your evaluator!")

if __name__ == "__main__":
    create_presentation()
